import React from 'react'

export const metadata = {
  title: "Service",
  description: "Generated by create next app",
};

const servicelayout = () => {
  return (
    <div>service layout</div>
  )
}

export default servicelayout