import React from 'react'


export const metadata = {
  title: "About Us",
  description: "Generated by create next app",
};

const aboutuslayout = () => {
  return (
    <div>aboutus layout</div>
  )
}

export default aboutuslayout